<a href="https://colab.research.google.com/github/Noors-lab/pytorch_stuffs/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# the libraries


In [2]:
import torch

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [37]:
# addition

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [38]:
# addtion longhand

torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [39]:
# substraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [40]:
# sub function
torch.sub(tensor_b , tensor_a)

tensor([4, 4, 4, 4])

In [41]:
# multiplication

tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [42]:
# mul longhand
torch.mul(tensor_a , tensor_b)

tensor([ 5, 12, 21, 32])

In [43]:
# division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [44]:
# div longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [45]:
# remainder module
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [46]:
# remainder longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [4]:
# exponents
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [6]:
# exponents longhand
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [9]:
# another way of longhand
tensor_a.add(tensor_b)


tensor([ 6,  8, 10, 12])

In [10]:
# another way of longhand
tensor_b.sub(tensor_a)

tensor([4, 4, 4, 4])